# Generated by Django 5.2.12 on 2026-03-23 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Только буквы, цифры, пробелы и дефисы', regex='^[\\w\\s\\-]+$')], verbose_name='Название')),
                ('kind', models.CharField(choices=[('salmon', 'Salmon'), ('cod', 'Cod'), ('carp', 'Carp'), ('perch', 'Perch'), ('other', 'Other')], max_length=10, verbose_name='Вид')),
                ('is_fresh', models.BooleanField(verbose_name='Свежая')),
                ('weight_grams', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Вес должен быть больше 0'), django.core.validators.MaxValueValidator(500000, message='Вес не может превышать 500 кг')], verbose_name='Вес (граммы)')),
                ('price_per_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Цена должна быть больше 0'), django.core.validators.MaxValueValidator(10000, message='Цена не может превышать 10000 руб/кг')], verbose_name='Цена за кг')),
                ('country', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Только буквы, пробелы и дефисы', regex='^[A-Za-zА-Яа-я\\s\\-]+$')], verbose_name='Страна происхождения')),
                ('quality_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Оценка от 1 до 5'), django.core.validators.MaxValueValidator(5, message='Оценка от 1 до 5')], verbose_name='Оценка качества')),
            ],
            options={
                'verbose_name': 'Рыбный товар',
                'verbose_name_plural': 'Рыбные товары',
            },
        ),
    ]
